### ISSUE TITLE
CCA and PS table display cuts off bottom row (Firefox & Chrome on Windows)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#900] opened 2019-07-18 22:53 UTC
I discovered this when selecting the maximum value (reddest point in the scatterplot, so not selecting in the table itself) on a sorted column (smallest to largest, so the selected row should be the last one at the bottom of the table) in the cars example.  Reversing the order of the sort brings the row to the top where it is now visible.

**Comment by pjcross** [comment] 2019-07-18 23:41
Now that I'm looking for it, it is also in the Parameter Space table too.  I checked the current release on Prod and this problem is new, Prod works as it should

**Comment by alexsielicki** [comment] 2019-07-19 20:51
I can duplicate this on my local system. Seems to be caused by upgrading slickgrid to the latest version 2.4.10. Reverting to 2.4.9 fixes it. Still looking into it and will file a bug with slickgrid.

**Comment by alexsielicki** [comment] 2019-07-19 21:04
Fixed by reverted slickgrid to version 2.4.9:
0df2a387edd7384c19c8f14232399836990913d1

Filed a bug with slickgrid regarding this:
6pac/SlickGrid/issues/400

**Closed by alexsielicki** 2019-07-19 21:04 UTC
Labels: CCA Model, PS Model, bug
