### ISSUE TITLE
Bookmark in CCA loses color-coding variable (new React/Python 3)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#913] opened 2019-10-14 21:04 UTC
Bookmark color-coding is set to index and has lost the variable that the bookmark was created with. (firefox on Windows)

**Comment by pjcross** [comment] 2020-01-13 21:43
When you exit the model and return to it, this same information is lost, whereas normally, the model returns to the same configuration that was there previously.  Perhaps the variable for the color-coding is not making it into the bookmark.

**Comment by alexsielicki** [comment] 2020-01-28 12:16
Duplicate of #922, which is now fixed. So closing this one too.

**Closed by alexsielicki** 2020-01-28 12:16 UTC
Labels: CCA Model, bug
