### ISSUE TITLE
Cannot add members to project

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#901] opened 2019-07-18 22:58 UTC
I put in the name, click add, it brings up the full name of the person, I say 'OK' and then the person is not added to the members list in the dialog.  (I tried clicking Save Changes to see if the person would be added anyways, the answer is no).

**Comment by alexsielicki** [comment] 2019-07-19 20:13
Caused by same issue as #902, fixed by same commit 733a152d2828baeeb7a3c2e1ed08b8f4f04fb45f

**Closed by alexsielicki** 2019-07-19 20:13 UTC
Labels: High Priority, bug
