### ISSUE TITLE
Rubberband drawn offset from expected starting point

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#304] opened 2015-01-09 21:30 UTC
Running on Firefox on Windows 7 with the new navbar version and the new reworked CCA model, the rubberband starts being drawn below and to the right of the arrow cursor instead of being aligned with the arrow tip as expected.

**Comment by tshead2** [comment] 2015-01-13 19:08
I've tested this in Safari 7.1.2, Chrome 39.0, and Firefox 34.0.5 on OSX, and it worked fine.  In Chrome only, the pointer does switch to a text-selection I-beam cursor, but the rubber band is still aligned correctly with the hotspot. So this may be a Windows-specific issue.

**Comment by FadingSwordsman** [comment] 2015-01-27 16:18
I was unable to reproduce in any browsers -- Firefox 14, 22, 32, and latest (34) on both Windows and Linux, as well as Chrome 39 in Windows/Linux. Closing for now, if this comes up again, will reopen.

**Comment by pjcross** [comment] 2015-02-04 00:11
I am seeing this on the latest version of the code in Chrome on Windows 7 for the CCA model.  I brought up the model, collapsed the window with the legend and tried to select some points in the scatterplot.

**Comment by pjcross** [comment] 2015-02-04 00:14
I do not see it in Firefox.  My Chrome browser is version 40.0.2214.93 m

**Comment by pjcross** [comment] 2015-02-04 00:20
I closed Chrome and restarted it and the behavior persists. I blew away the cache and browsing history and the bug persists.

**Comment by pjcross** [comment] 2015-02-04 23:26
The source of the problem was that I had changed my scaling in the browser and Chrome is not correctly passing back the right coordinates to the client.  This is the source of many of the Chrome bugs I have found (i.e. resetting the scale fixes them).

**Closed** 2015-02-05 22:00 UTC
Labels: bug, CCA Model
