### ISSUE TITLE
Cannot delete bookmarks

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#902] opened 2019-07-18 23:31 UTC
I've tried deleting the bookmark both at the project level and at the model level.  Both times it warns me that the deletion cannot be undone.  I say 'OK' and the dialog goes away, but the bookmark remains.  Just as with adding project members, I'm not sure where the issue lies (server or client)...

**Comment by alexsielicki** [comment] 2019-07-19 17:45
Editing bookmarks also doesn't work

**Comment by alexsielicki** [comment] 2019-07-19 17:52
Seems to be a front-end issue since I don't even see a call being made to the API when deleting or editing bookmarks. Looking into it now.

**Comment by alexsielicki** [comment] 2019-07-19 20:11
This was caused by commit b61c4ce291d3ce6588f3f19f3b1d583d841b2ea5 which was trying to work around issues due to having multiple modals open at once. Bootstrap does not support multiple modals at the same time:
https://getbootstrap.com/docs/4.3/components/modal/#how-it-works
"Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences."

Instead of using a second dialog for error messages, use inline form validation with bootstrap's form components:
https://getbootstrap.com/docs/4.3/components/forms/#validation

This fix also fixes #901 and #904

**Comment by alexsielicki** [comment] 2019-07-19 20:12
Fixed by 733a152d2828baeeb7a3c2e1ed08b8f4f04fb45f

**Closed by alexsielicki** 2019-07-19 20:12 UTC
Labels: High Priority, bug
