### ISSUE TITLE
Directory access errors during remote file browsing

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1026] opened 2021-06-15 19:27 UTC
Although the remote browser works and I can traverse the directory hierarchy, the log shows a series of cherrypy errors saying that the remote access for reading the directory failed.  We need to figure out what is the source of these failures.

**Comment by Spurs20** [comment] 2022-02-24 18:17
Closing this because it can't be reproduced in any model type.

**Closed by Spurs20** 2022-02-24 18:17 UTC
Labels: bug
